import { useEffect, useState, useRef, useCallback } from "react";
import { useParams, Link } from "react-router-dom";
import { api } from "@/lib/api";
import { log } from "@/lib/log";
import { motion, AnimatePresence } from "framer-motion";
import {
  ArrowLeft, Loader2, FileDown, RefreshCw, MessageSquare, Send, Trash2,
  Briefcase, ShieldAlert, ExternalLink, Sparkles, Share2, Mail, Copy, MapPin,
  Sun, Sunset, Moon,
} from "lucide-react";
import {
  Accordion, AccordionContent, AccordionItem, AccordionTrigger,
} from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Checkbox } from "@/components/ui/checkbox";
import { Skeleton } from "@/components/ui/skeleton";

import DestinationHero from "@/components/DestinationHero";
import DayHeader from "@/components/DayHeader";
import ActivityCard from "@/components/ActivityCard";
import DailyBudgetSummary from "@/components/DailyBudgetSummary";
import DayWeatherBanner from "@/components/DayWeatherBanner";
import WeatherTab from "@/components/WeatherTab";
import BudgetTab from "@/components/BudgetTab";
import SafetyTab from "@/components/SafetyTab";
import EnhancedMapTab from "@/components/EnhancedMapTab";

import { toast } from "sonner";
import jsPDF from "jspdf";

export default function Itinerary() {
  const { id } = useParams();
  const [trip, setTrip] = useState(null);
  const [weather, setWeather] = useState(null);
  const [loading, setLoading] = useState(true);
  const [packing, setPacking] = useState({});
  const [regenerating, setRegenerating] = useState(false);
  const [regeneratingDay, setRegeneratingDay] = useState(null);
  const [shareInfo, setShareInfo] = useState(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const { data } = await api.get(`/trips/${id}`);
      setTrip(data);
      if (data.share_id) setShareInfo({ share_id: data.share_id, is_public: !!data.is_public });
      try {
        const w = await api.get(`/weather`, {
          params: { destination: data.destination, days: data.days, start_date: data.start_date || undefined },
        });
        setWeather(w.data);
      } catch (err) {
        log.warn("Weather fetch failed (non-blocking)", err);
      }
    } catch (err) {
      log.error("Failed to load trip", err);
      toast.error("Trip not found");
    } finally {
      setLoading(false);
    }
  }, [id]);
  useEffect(() => { load(); }, [load]);

  const regen = async () => {
    setRegenerating(true);
    try {
      const { data } = await api.post(`/trips/${id}/regenerate`);
      setTrip(data);
      toast.success("Itinerary regenerated");
    } catch (e) { toast.error("Failed to regenerate"); }
    finally { setRegenerating(false); }
  };

  const regenerateDay = useCallback(async (dayNumber, instruction) => {
    setRegeneratingDay(dayNumber);
    try {
      const { data } = await api.post(`/trips/${id}/regenerate-day`, {
        day_number: dayNumber,
        instruction: instruction || "",
      });
      setTrip((t) => {
        if (!t) return t;
        const newDays = (t.itinerary.days || []).map((d) =>
          d.day === dayNumber ? data.day : d
        );
        return { ...t, itinerary: { ...t.itinerary, days: newDays } };
      });
      toast.success(`Day ${dayNumber} regenerated`);
    } catch (e) {
      toast.error("Failed to regenerate day");
    } finally {
      setRegeneratingDay(null);
    }
  }, [id]);

  const toggleShare = async () => {
    try {
      const { data } = await api.post(`/trips/${id}/share`);
      setShareInfo(data);
      if (data.is_public) {
        const url = `${window.location.origin}/share/${data.share_id}`;
        await navigator.clipboard.writeText(url).catch(() => {});
        toast.success("Public link copied to clipboard!");
      } else {
        toast.success("Trip is now private");
      }
    } catch {
      toast.error("Failed to toggle share");
    }
  };

  const copyShareLink = async () => {
    if (!shareInfo?.share_id) return;
    const url = `${window.location.origin}/share/${shareInfo.share_id}`;
    await navigator.clipboard.writeText(url);
    toast.success("Link copied!");
  };

  const emailItinerary = () => {
    if (!trip) return;
    const it = trip.itinerary || {};
    const url = shareInfo?.is_public ? `${window.location.origin}/share/${shareInfo.share_id}` : "";
    const lines = [
      `Trip: ${trip.destination} (${trip.days} days)`,
      `Budget: ${trip.currency} ${Number(trip.budget).toLocaleString()}`,
      "",
      it.summary || "",
      "",
      ...(it.days || []).map((d) => `Day ${d.day} — ${d.title || ""}`),
      "",
      url ? `View full plan: ${url}` : "Generated by Travel Planner AI",
    ];
    const subject = encodeURIComponent(`My ${trip.destination} itinerary`);
    const body = encodeURIComponent(lines.join("\n"));
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  const exportPDF = () => {
    if (!trip?.itinerary) return;
    const doc = new jsPDF();
    const it = trip.itinerary;
    let y = 15;
    doc.setFontSize(20); doc.text(`${trip.destination} — ${trip.days} days`, 15, y); y += 9;
    doc.setFontSize(11); doc.setTextColor(120);
    doc.text(`${trip.travel_type} • ${trip.pace} • ${trip.currency} ${trip.budget}`, 15, y); y += 8;
    doc.setTextColor(40); doc.setFontSize(11);
    const summary = doc.splitTextToSize(it.summary || "", 180);
    doc.text(summary, 15, y); y += summary.length * 6 + 4;
    (it.days || []).forEach((d) => {
      if (y > 260) { doc.addPage(); y = 15; }
      doc.setFontSize(14); doc.setTextColor(180, 30, 200);
      doc.text(`Day ${d.day}: ${d.title || ""}`, 15, y); y += 7;
      doc.setTextColor(40); doc.setFontSize(10);
      ["morning","afternoon","evening"].forEach((slot) => {
        const s = d[slot]; if (!s) return;
        doc.setFont(undefined, "bold"); doc.text(`${slot.toUpperCase()} — ${s.time || ""}`, 15, y); y += 5;
        doc.setFont(undefined, "normal");
        const txt = doc.splitTextToSize(`${s.place_name || s.activity || ""} @ ${s.location || ""} — ${trip.currency} ${s.cost || 0}. ${s.tips || ""}`, 180);
        doc.text(txt, 15, y); y += txt.length * 5 + 2;
        if (y > 270) { doc.addPage(); y = 15; }
      });
      y += 3;
    });
    doc.save(`${trip.destination}-itinerary.pdf`);
    toast.success("PDF downloaded");
  };

  if (loading) return (
    <div className="max-w-6xl mx-auto px-5 py-10 space-y-6">
      <Skeleton className="h-12 w-72 bg-white/5" />
      <Skeleton className="h-64 w-full bg-white/5 rounded-3xl" />
      <Skeleton className="h-12 w-full bg-white/5 rounded-2xl" />
      {Array.from({ length: 3 }).map((_, i) => (
        <Skeleton key={i} className="h-40 w-full bg-white/5 rounded-3xl" />
      ))}
    </div>
  );
  if (!trip) return null;

  const it = trip.itinerary || {};

  return (
    <main data-testid="itinerary-page" className="max-w-6xl mx-auto px-5 md:px-8 py-8">
      <Link to="/dashboard" className="inline-flex items-center text-white/60 hover:text-white text-sm mb-6">
        <ArrowLeft className="w-4 h-4 mr-1.5"/> Back to dashboard
      </Link>

      {/* Header */}
      <DestinationHero query={trip.destination} height="h-48 md:h-64" />
      <div className="glass rounded-3xl p-6 md:p-8 mb-8 mt-4">
        <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-6">
          <div className="flex-1">
            <div className="text-xs font-mono-acc uppercase tracking-widest text-fuchsia-300 mb-2">
              {trip.days} days • {trip.travel_type} • {trip.pace}
              {trip.source && <span> • from {trip.source}</span>}
            </div>
            <h1 className="font-display text-4xl md:text-5xl tracking-tight">{trip.destination}</h1>
            <p className="text-white/70 mt-3 max-w-2xl">{it.summary}</p>
            <div className="flex flex-wrap gap-2 mt-4">
              {(it.highlights || []).slice(0, 5).map((h) => (
                <span key={h} className="text-xs px-2.5 py-1 rounded-full bg-fuchsia-500/10 border border-fuchsia-500/20 text-fuchsia-200">{h}</span>
              ))}
            </div>
          </div>
          <div className="flex flex-col gap-2 min-w-fit">
            <Button data-testid="itinerary-share" onClick={toggleShare} variant="outline" className="bg-white/5 border-white/10 text-white hover:bg-white/10">
              <Share2 className="w-4 h-4 mr-2"/> {shareInfo?.is_public ? "Stop sharing" : "Share publicly"}
            </Button>
            {shareInfo?.is_public && (
              <Button data-testid="itinerary-copy-link" onClick={copyShareLink} variant="outline" className="bg-fuchsia-500/10 border-fuchsia-500/30 text-fuchsia-200 hover:bg-fuchsia-500/20">
                <Copy className="w-4 h-4 mr-2"/> Copy link
              </Button>
            )}
            <Button data-testid="itinerary-email" onClick={emailItinerary} variant="outline" className="bg-white/5 border-white/10 text-white hover:bg-white/10">
              <Mail className="w-4 h-4 mr-2"/> Email
            </Button>
            <Button data-testid="itinerary-export" onClick={exportPDF} variant="outline" className="bg-white/5 border-white/10 text-white hover:bg-white/10">
              <FileDown className="w-4 h-4 mr-2"/> Export PDF
            </Button>
            <Button data-testid="itinerary-regenerate" onClick={regen} disabled={regenerating} variant="outline" className="bg-white/5 border-white/10 text-white hover:bg-white/10">
              {regenerating ? <Loader2 className="w-4 h-4 mr-2 animate-spin"/> : <RefreshCw className="w-4 h-4 mr-2"/>} Regenerate
            </Button>
            <Button
              data-testid="itinerary-maps"
              onClick={() => window.open(`https://www.google.com/maps/search/${encodeURIComponent(trip.destination)}`, "_blank")}
              variant="outline" className="bg-white/5 border-white/10 text-white hover:bg-white/10"
            ><ExternalLink className="w-4 h-4 mr-2"/> Open in Maps</Button>
          </div>
        </div>
      </div>

      <Tabs defaultValue="timeline" className="w-full">
        <TabsList className="bg-white/5 border border-white/10 mb-6 flex-wrap h-auto">
          <TabsTrigger data-testid="tab-timeline" value="timeline" className="data-[state=active]:bg-fuchsia-500/20 data-[state=active]:text-white">Timeline</TabsTrigger>
          <TabsTrigger data-testid="tab-budget" value="budget" className="data-[state=active]:bg-fuchsia-500/20 data-[state=active]:text-white">Budget</TabsTrigger>
          <TabsTrigger data-testid="tab-weather" value="weather" className="data-[state=active]:bg-fuchsia-500/20 data-[state=active]:text-white">Weather</TabsTrigger>
          <TabsTrigger data-testid="tab-packing" value="packing" className="data-[state=active]:bg-fuchsia-500/20 data-[state=active]:text-white">Packing</TabsTrigger>
          <TabsTrigger data-testid="tab-food" value="food" className="data-[state=active]:bg-fuchsia-500/20 data-[state=active]:text-white">Food</TabsTrigger>
          <TabsTrigger data-testid="tab-map" value="map" className="data-[state=active]:bg-fuchsia-500/20 data-[state=active]:text-white">Map</TabsTrigger>
          <TabsTrigger data-testid="tab-safety" value="safety" className="data-[state=active]:bg-fuchsia-500/20 data-[state=active]:text-white">Safety</TabsTrigger>
          <TabsTrigger data-testid="tab-chat" value="chat" className="data-[state=active]:bg-fuchsia-500/20 data-[state=active]:text-white">AI Chat</TabsTrigger>
        </TabsList>

        {/* Timeline */}
        <TabsContent value="timeline">
          <div className="relative pl-8 before:absolute before:inset-y-0 before:left-[14px] before:w-[2px] before:bg-gradient-to-b before:from-fuchsia-500 before:via-purple-500/60 before:to-purple-500/0">
            <Accordion type="multiple" defaultValue={["day-1"]} className="space-y-4">
              {(it.days || []).map((d, i) => {
                const weatherDay = (weather?.forecast || []).find((w) => w.day === d.day);
                return (
                  <motion.div
                    key={d.day} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.05 }}
                  >
                    <AccordionItem value={`day-${d.day}`} className="border-0 -ml-8">
                      <div className="relative">
                        <div className="absolute -left-[26px] top-5 w-3 h-3 rounded-full bg-fuchsia-400 shadow-[0_0_12px_rgba(255,0,255,0.7)]" />
                        <div className="glass rounded-2xl overflow-hidden">
                          <AccordionTrigger data-testid={`day-${d.day}-trigger`} className="px-6 py-5 hover:no-underline">
                            <DayHeader
                              dayNumber={d.day}
                              startDate={trip.start_date}
                              destination={trip.destination_location?.city || trip.destination}
                              currency={trip.currency}
                              estimatedCost={d.estimated_cost}
                            />
                          </AccordionTrigger>
                          <AccordionContent className="px-6 pb-6">
                            <DayWeatherBanner weatherDay={weatherDay} />
                            {d.weather_aware_note && (
                              <div className="text-xs text-fuchsia-200/70 italic mb-3 -mt-2 flex items-center gap-1.5">
                                <Sparkles className="w-3 h-3" /> {d.weather_aware_note}
                              </div>
                            )}
                            <div className="space-y-3">
                              <ActivityCard slot="morning"   data={d.morning}   currency={trip.currency} destination={trip.destination} />
                              <ActivityCard slot="afternoon" data={d.afternoon} currency={trip.currency} destination={trip.destination} />
                              <ActivityCard slot="evening"   data={d.evening}   currency={trip.currency} destination={trip.destination} />
                              {d.travel_time_notes && <p className="text-xs text-white/50 italic">{d.travel_time_notes}</p>}
                              <DailyBudgetSummary daily={d.daily_budget} currency={trip.currency} estimatedCost={d.estimated_cost} />

                              {/* Per-day regenerate */}
                              <div className="flex justify-end pt-2">
                                <button
                                  type="button"
                                  data-testid={`day-${d.day}-regenerate`}
                                  onClick={() => regenerateDay(d.day, "Suggest different attractions and meal options for this day.")}
                                  disabled={regeneratingDay === d.day}
                                  className="text-xs px-3 py-1.5 rounded-full bg-white/5 border border-white/10 hover:bg-white/10 text-white/70 inline-flex items-center gap-1.5 disabled:opacity-50"
                                >
                                  {regeneratingDay === d.day
                                    ? <Loader2 className="w-3 h-3 animate-spin"/>
                                    : <RefreshCw className="w-3 h-3"/>}
                                  Regenerate day
                                </button>
                              </div>
                            </div>
                          </AccordionContent>
                        </div>
                      </div>
                    </AccordionItem>
                  </motion.div>
                );
              })}
            </Accordion>
          </div>
        </TabsContent>

        <TabsContent value="budget"><BudgetTab trip={trip} /></TabsContent>

        <TabsContent value="weather"><WeatherTab weather={weather} destination={trip.destination} /></TabsContent>

        {/* Packing */}
        <TabsContent value="packing">
          <div className="glass rounded-3xl p-6">
            <div className="flex items-center gap-3 mb-2"><Briefcase className="w-5 h-5 text-fuchsia-300"/><h3 className="font-display text-2xl">Packing list</h3></div>
            <p className="text-white/60 text-sm mb-5">Tailored to weather, duration & activities</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
              {(it.packing_list || []).map((item, i) => (
                <label key={item} className="flex items-center gap-3 px-4 py-3 rounded-xl bg-white/5 border border-white/10 hover:border-fuchsia-500/40 transition cursor-pointer">
                  <Checkbox
                    data-testid={`packing-${i}`}
                    checked={!!packing[i]}
                    onCheckedChange={(v) => setPacking({ ...packing, [i]: v })}
                    className="data-[state=checked]:bg-fuchsia-500 data-[state=checked]:border-fuchsia-500"
                  />
                  <span className={packing[i] ? "line-through text-white/40" : ""}>{item}</span>
                </label>
              ))}
            </div>
          </div>
        </TabsContent>

        {/* Food */}
        <TabsContent value="food">
          <div className="glass rounded-3xl p-6">
            <h3 className="font-display text-2xl mb-1">Restaurant picks</h3>
            <p className="text-white/60 text-sm mb-5">Curated by AI for {trip.food_pref} travelers</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {(it.restaurants || []).map((r) => (
                <div key={`${r.name}-${r.meal}`} className="rounded-2xl p-4 bg-white/5 border border-white/10">
                  <div className="flex items-start justify-between">
                    <div>
                      <div className="font-display text-lg">{r.name}</div>
                      <div className="text-xs text-white/50 mt-0.5">{r.cuisine} • {r.meal} • {r.price_level}</div>
                    </div>
                    <div className="text-fuchsia-300 font-mono-acc">{r.rating?.toFixed?.(1) ?? r.rating}★</div>
                  </div>
                </div>
              ))}
            </div>
            {it.hidden_gems?.length > 0 && (
              <div className="mt-6">
                <div className="flex items-center gap-2 mb-3"><Sparkles className="w-4 h-4 text-fuchsia-300"/><h4 className="font-display text-xl">Hidden gems</h4></div>
                <ul className="space-y-2">
                  {it.hidden_gems.map((g) => <li key={g} className="text-sm text-white/70 flex gap-2"><MapPin className="w-4 h-4 text-fuchsia-300 mt-0.5 flex-shrink-0"/>{g}</li>)}
                </ul>
              </div>
            )}
          </div>
        </TabsContent>

        <TabsContent value="map"><EnhancedMapTab trip={trip} /></TabsContent>

        <TabsContent value="safety"><SafetyTab trip={trip} weather={weather} /></TabsContent>

        <TabsContent value="chat">
          <ChatPanel tripId={trip.id} destination={trip.destination} onDayRegen={regenerateDay} days={it.days || []} />
        </TabsContent>
      </Tabs>
    </main>
  );
}

function ChatPanel({ tripId, destination, onDayRegen, days }) {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [sending, setSending] = useState(false);
  const endRef = useRef(null);

  const load = useCallback(async () => {
    const { data } = await api.get("/chat/history", { params: { trip_id: tripId } });
    setMessages(data);
  }, [tripId]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, sending]);

  const detectDayRequest = (text) => {
    // detect explicit day target eg "day 3", "today"
    const m = text.match(/day\s+(\d+)/i);
    if (m) return parseInt(m[1], 10);
    return null;
  };

  const send = async (e) => {
    e?.preventDefault();
    if (!input.trim() || sending) return;
    const msg = input.trim();
    setInput("");
    setSending(true);

    // Check if the user is asking to modify a specific day
    const dayN = detectDayRequest(msg);
    const intent = /\b(replace|swap|move|change|remove|add|find nearby|cheaper)\b/i.test(msg);

    setMessages((m) => [...m, { id: "tmp", message: msg, response: null }]);
    try {
      if (dayN && intent && days.find((d) => d.day === dayN)) {
        await onDayRegen?.(dayN, msg);
        setMessages((m) => [
          ...m.slice(0, -1),
          { id: `local-${Date.now()}`, message: msg, response: `Done — Day ${dayN} updated based on your instruction.` },
        ]);
      } else {
        const { data } = await api.post("/chat", { trip_id: tripId, message: msg });
        setMessages((m) => [...m.slice(0, -1), data]);
      }
    } catch (err) {
      log.error("Chat send failed", err);
      toast.error("Chat failed");
      setMessages((m) => m.slice(0, -1));
    } finally { setSending(false); }
  };

  const clear = async () => {
    await api.delete("/chat/history", { params: { trip_id: tripId } });
    setMessages([]);
    toast.success("Chat cleared");
  };

  const suggestions = [
    "Find nearby cafes",
    "Replace today's museum",
    "Add nightlife on day 2",
    "Remove shopping",
    "Show cheaper restaurants",
    "Move beach to tomorrow",
  ];

  return (
    <div className="glass rounded-3xl p-5 flex flex-col h-[640px]">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2"><MessageSquare className="w-5 h-5 text-fuchsia-300"/><h3 className="font-display text-xl">Travel Assistant</h3></div>
        <Button onClick={clear} variant="ghost" size="sm" className="text-white/50 hover:text-white" data-testid="chat-clear"><Trash2 className="w-4 h-4 mr-1.5"/>Clear</Button>
      </div>

      <div className="flex-1 overflow-y-auto space-y-4 pr-2 scrollbar-thin">
        {messages.length === 0 && (
          <div className="text-center text-white/50 py-10">
            <Sparkles className="w-10 h-10 mx-auto mb-3 text-fuchsia-300"/>
            <p>Ask me anything about your {destination} trip!</p>
            <p className="text-xs text-white/40 mt-2">Tip: mention a day number (e.g. <span className="text-fuchsia-300">&quot;replace museum on day 2&quot;</span>) and I&apos;ll regenerate only that day.</p>
            <div className="flex flex-wrap gap-2 justify-center mt-4">
              {suggestions.map((s) => (
                <button key={s} onClick={() => setInput(s)} className="text-xs px-3 py-1.5 rounded-full bg-white/5 border border-white/10 hover:bg-white/10">
                  {s}
                </button>
              ))}
            </div>
          </div>
        )}
        <AnimatePresence>
          {messages.map((m) => (
            <motion.div key={m.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="space-y-2">
              <div className="flex justify-end">
                <div className="max-w-[80%] px-4 py-2.5 rounded-2xl bg-white/10 text-white rounded-br-sm">{m.message}</div>
              </div>
              <div className="flex">
                <div className="max-w-[80%] px-4 py-2.5 rounded-2xl bg-gradient-to-br from-fuchsia-500/15 to-purple-600/15 border border-purple-500/30 rounded-bl-sm whitespace-pre-wrap">
                  {m.response || <Loader2 className="w-4 h-4 animate-spin"/>}
                </div>
              </div>
            </motion.div>
          ))}
        </AnimatePresence>
        <div ref={endRef} />
      </div>

      <form onSubmit={send} className="mt-4 flex gap-2">
        <input
          data-testid="chat-input"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask anything about your trip…"
          className="flex-1 px-4 py-3 rounded-full bg-white/5 border border-white/10 text-white focus:outline-none focus:border-fuchsia-500/50"
        />
        <Button data-testid="chat-send" type="submit" disabled={sending || !input.trim()} className="btn-primary text-white border-0 rounded-full px-5">
          {sending ? <Loader2 className="w-4 h-4 animate-spin"/> : <Send className="w-4 h-4"/>}
        </Button>
      </form>
    </div>
  );
}

// Unused decorative imports retained for icon set
void Sun; void Sunset; void Moon; void ShieldAlert;
